In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
files=["subject102.DAT","subject103.DAT","subject104.DAT","subject105.DAT","subject106.DAT","subject107.DAT","subject108.DAT","subject109.DAT"]
data=pd.read_csv(r"C:\Users\vivek\Downloads\SMAI\Project\PAMAP2_Dataset\Protocol\subject101.DAT",sep=" ",header=None)
data=data.interpolate(method ='linear', limit_direction ='forward').copy()
for i in range(len(files)):
    path="C://Users//vivek//Downloads//SMAI//Project//PAMAP2_Dataset//Protocol//"+files[i]
    temp=pd.read_csv(path,sep=" ",header=None)
    temp=temp.interpolate(method ='linear').copy()
    data=data.append(temp, ignore_index=True)

C:\Users\vivek\AppData\Local\Temp\ipykernel_11508\1559619422.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)
C:\Users\vivek\AppData\Local\Temp\ipykernel_11508\1559619422.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)
C:\Users\vivek\AppData\Local\Temp\ipykernel_11508\1559619422.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)
C:\Users\vivek\AppData\Local\Temp\ipykernel_11508\1559619422.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)
C:\Users\vivek\AppData\Local\Temp\ipykernel_11508\1559619422.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)
C:\Users\vivek\AppData\Local\Temp\ipykernel_11508\1559619422.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)
C:\Users\vivek\AppData\Local\Temp\ipykernel_11508\1559619422.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)
C:\Users\vivek\AppData\Local\Temp\ipykernel_11508\1559619422.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)

In [3]:
data.rename(columns = {1:'activity'}, inplace = True)
data

,0,activity,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
0,8.38,0,104.0,30.0000,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.008300,0.009250,-0.017580,-61.1888,-38.95990,-58.143800,1.000000,0.000000,0.000000,0.000000
1,8.39,0,104.0,30.0000,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.006577,-0.004638,0.000368,-59.8479,-38.89190,-58.525300,1.000000,0.000000,0.000000,0.000000
2,8.40,0,104.0,30.0000,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.003014,0.000148,0.022495,-60.7361,-39.41380,-58.399900,1.000000,0.000000,0.000000,0.000000
3,8.41,0,104.0,30.0000,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,0.003175,-0.020301,0.011275,-60.4091,-38.76350,-58.395600,1.000000,0.000000,0.000000,0.000000
4,8.42,0,104.0,30.0000,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,0.012698,-0.014303,-0.002823,-61.5199,-39.38790,-58.269400,1.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2872528,100.19,0,161.0,25.1875,-4.71493,10.22250,4.66893,-5.04654,9.94944,4.50736,...,-0.037788,-0.062676,-0.127084,-46.5153,3.58240,-0.035995,0.598531,0.033615,0.799791,-0.031075
2872529,100.20,0,161.0,25.1875,-4.95932,10.37130,4.12594,-4.96890,10.29620,4.43102,...,-0.068904,-0.027006,-0.089808,-45.7474,3.54453,0.108583,0.598428,0.033012,0.799933,-0.030018
2872530,100.21,0,161.0,25.1875,-4.93997,9.83615,3.70468,-5.04613,10.35690,4.14405,...,-0.070888,-0.038024,-0.064709,-46.3997,4.22078,0.105504,0.598233,0.033172,0.800095,-0.029416
2872531,100.22,0,161.0,25.1875,-4.64941,9.11129,3.51904,-5.06854,9.75268,3.87359,...,0.018961,-0.025796,-0.064357,-46.5282,4.48593,0.530240,0.598116,0.033427,0.800180,-0.029208
2872532,100.23,0,161.0,25.1875,-4.09726,8.15642,3.29961,-4.73244,8.82870,3.54305,...,-0.027472,0.011866,-0.042858,-46.2704,4.21475,0.247798,0.598119,0.033685,0.800188,-0.028602

In [4]:
data=data.dropna() 
data.shape

activity_id = {1:'lying', 2:'sitting', 3:'standing',
              4:'walking', 5:'running', 6:'cycling', 7:'Nordic walking', 
              12:'ascending stairs', 13:'descending stairs', 16:'vacuum cleaning',
              17:'ironing', 24:'rope jumping'}
data=data[data['activity'].isin(activity_id.keys())]
data=data[data.columns[:-34]]
data

,0,activity,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
2928,37.66,1,100.0,30.375,2.21530,8.27915,5.58753,2.24689,8.55387,5.77143,-0.004750,0.037579,-0.011145,8.93200,-67.9326,-19.9755,1.000000,0.000000,0.000000,0.000000
2929,37.67,1,100.0,30.375,2.29196,7.67288,5.74467,2.27373,8.14592,5.78739,-0.171710,0.025479,-0.009538,9.58300,-67.9584,-20.9091,1.000000,0.000000,0.000000,0.000000
2930,37.68,1,100.0,30.375,2.29090,7.14240,5.82342,2.26966,7.66268,5.78846,-0.238241,0.011214,0.000831,9.05516,-67.4017,-19.5083,1.000000,0.000000,0.000000,0.000000
2931,37.69,1,100.0,30.375,2.21800,7.14365,5.89930,2.22177,7.25535,5.88000,-0.192912,0.019053,0.013374,9.92698,-67.4387,-20.5602,1.000000,0.000000,0.000000,0.000000
2932,37.70,1,100.0,30.375,2.30106,7.25857,6.09259,2.20720,7.24042,5.95555,-0.069961,-0.018328,0.004582,9.15626,-67.1825,-20.0857,1.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2872015,95.06,24,162.0,25.125,4.99466,6.01881,5.59830,4.90787,6.05780,5.68357,-0.289166,-0.110170,0.238570,-4.79353,-18.1271,-48.2695,0.823022,-0.256932,0.401650,0.308704
2872016,95.07,24,162.0,25.125,5.02764,5.90369,5.48372,4.89090,5.95209,5.56301,-0.275411,-0.128358,0.267409,-4.54101,-18.0169,-48.9268,0.823742,-0.255166,0.401881,0.307947
2872017,95.08,24,162.0,25.125,5.06409,5.71370,5.48491,4.97981,5.87584,5.45738,-0.289885,-0.126548,0.281483,-4.17401,-17.9121,-48.4032,0.824497,-0.253507,0.402103,0.307006
2872018,95.09,24,162.0,25.125,5.13914,5.63724,5.48629,4.97690,5.69448,5.29167,-0.234417,-0.101485,0.275497,-4.66091,-18.2588,-49.0563,0.824995,-0.252236,0.402400,0.306323
2872019,95.10,24,162.0,25.125,5.00812,5.40645,5.02326,4.97362,5.45272,5.14120,-0.260924,-0.093849,0.266205,-5.05008,-17.6169,-48.1408,0.825532,-0.250699,0.402659,0.305797

In [5]:
from sklearn.model_selection import train_test_split
y=data[data.columns[1]]
X=data[data.columns[2:]]
for i in X.columns:
    X[i] = (X[i] - X[i].mean()) / X[i].std()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

C:\Users\vivek\AppData\Local\Temp\ipykernel_11508\1556569103.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[i] = (X[i] - X[i].mean()) / X[i].std()

In [6]:
X_test

,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1195119,-0.166265,0.521827,-0.887456,-0.549762,-0.813313,-0.820867,-0.423346,-0.929230,-0.624116,-0.251519,-0.053641,0.948841,0.065352,0.169109,0.427561,0.875858,-0.850046,-0.834411
1918099,-0.166265,0.765674,-0.176531,0.162486,-2.600110,-0.184403,0.332406,-2.319452,-0.509853,-0.484227,0.034570,0.168788,-0.210343,1.787449,-1.494045,-1.674549,1.656397,1.172008
1686094,0.833975,1.079191,0.415119,-0.141233,-0.911392,0.539384,-0.249290,-0.897603,0.009764,-0.242831,0.248714,0.358166,-1.690217,1.523302,0.607596,-0.978203,-0.663373,-0.614581
394387,-1.166504,0.521827,1.907785,-0.160403,0.631586,1.926230,-0.173095,0.689279,0.003413,-0.094142,0.008490,-0.595937,0.660404,-1.010509,1.086647,-0.088117,1.566748,0.343740
570069,-0.388540,0.626333,-0.629303,0.055050,-0.577335,-0.713806,-0.002176,-0.555616,1.225828,0.223774,0.255279,0.617080,-0.455912,2.019204,-1.084569,-1.516999,0.603759,1.436153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329726,2.426950,-1.289603,1.536781,0.607939,-1.375627,1.561742,0.479132,-1.357684,-0.460855,2.210307,1.622625,-0.082473,-2.074005,1.258331,1.406770,0.113856,0.363899,0.084799
122611,0.537608,0.452157,0.248931,0.587491,0.354573,0.190572,0.535263,0.275869,-0.157363,-0.160038,-0.532323,0.168565,-0.287217,-0.456815,1.406770,0.113856,0.363899,0.084799
748470,0.352378,-1.846966,0.222856,-0.266951,1.127371,0.254360,-0.400009,0.681330,0.237118,0.217345,-0.149150,-0.013589,-0.002554,-1.332534,-1.735246,0.691458,-0.016628,-1.620865
494497,-0.833091,0.939850,0.116826,0.421209,1.013832,0.239447,0.439085,1.015314,-1.176915,1.359561,0.897558,-1.698278,-0.817803,-1.787148,-1.754202,0.190747,-0.418130,-1.613275
2356801,-0.277402,0.034135,-1.214797,0.037629,-0.493796,-1.222358,0.003655,-0.451405,0.045161,-0.447067,1.289379,1.507850,0.424807,-0.612675,-1.545230,2.086712,0.221928,-1.130253

In [7]:
tx1=X_train[:int(len(X_train)/5)].copy()
tx2=X_train[int(len(X_train)/5):int(2*len(X_train)/5)].copy()
tx3=X_train[int(2*len(X_train)/5):int(3*len(X_train)/5)].copy()
tx4=X_train[int(3*len(X_train)/5):int(4*len(X_train)/5)].copy()
tx5=X_train[int(4*len(X_train)/5):].copy()
ty1=y_train[:int(len(y_train)/5)].copy()
ty2=y_train[int(len(y_train)/5):int(2*len(y_train)/5)].copy()
ty3=y_train[int(2*len(y_train)/5):int(3*len(y_train)/5)].copy()
ty4=y_train[int(3*len(y_train)/5):int(4*len(y_train)/5)].copy()
ty5=y_train[int(4*len(y_train)/5):].copy()
training_x=[tx1,tx2,tx3,tx4,tx5]
training_y=[ty1,ty2,ty3,ty4,ty5]

In [8]:
def data(i):
    temp_x=pd.DataFrame()
    temp_y=pd.DataFrame()
    val_x=pd.DataFrame()
    val_y=pd.DataFrame()
    for j in range(5):
        if (i!=j):
            temp_x=pd.concat([temp_x,training_x[j]])
            temp_y=pd.concat([temp_y,training_y[j]])
        else:
            val_x=pd.concat([val_x,training_x[j]])
            val_y=pd.concat([val_y,training_y[j]])
    return temp_x,temp_y,val_x,val_y

In [9]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import time
scores=pd.DataFrame(columns=["Fold.no","Training Score","Validation Score","Test Score"])
classifiers=[]
for i in range(5):
    start_time = time.time()
    data_x,data_y,v_x,v_y=data(i)
    print("data",(time.time() - start_time))
    temp=pd.concat([data_x,data_y], axis=1)
    temp=temp.sample(n=425000)
    data_x=temp[temp.columns[:-1]]
    data_y=temp[temp.columns[-1]]
    temp=pd.concat([v_x,v_y], axis=1)
    temp=temp.sample(n=75000)
    v_x=temp[temp.columns[:-1]]
    v_y=temp[temp.columns[-1]]
    temp=pd.concat([X_test,y_test], axis=1)
    temp=temp.sample(n=75000)
    x3=temp[temp.columns[:-1]]
    y3=temp[temp.columns[-1]]
    print(data_x.shape,v_x.shape,x3.shape)
#     x1=pca.fit_transform(data_x)
#     x2=pca.fit_transform(v_x)
#     x3=pca.fit_transform(x3)
#     print("PCA",(time.time() - start_time))
#     x1=pd.DataFrame(x1)
#     x2=pd.DataFrame(x2)
#     x3=pd.DataFrame(x3)
    
    y_tr=list(data_y)
    base = DecisionTreeClassifier(max_depth=9)
    classifier = AdaBoostClassifier(base_estimator=base,n_estimators=100)
    classifier.fit(data_x, data_y)
    print(i,(time.time() - start_time))
    vy_pred = classifier.predict(v_x)
    sc2=accuracy_score(v_y, vy_pred)
    try_pred = classifier.predict(data_x)
    sc1=accuracy_score(data_y, try_pred)
    tey_pred = classifier.predict(x3)
    sc3=accuracy_score(y3, tey_pred)
    classifiers.append(classifier)
    print(sc1,sc2,sc3,(time.time() - start_time))
    scores.loc[len(scores)]=[i,sc1,sc2,sc3]
print("Best Test Accuracy is :", max(scores['Test Score']))
scores

data 0.19029617309570312
(425000, 18) (75000, 18) (75000, 18)
0 1353.1782698631287
0.9848823529411764 0.9811733333333333 0.9812 1383.5657172203064
data 0.275836706161499
(425000, 18) (75000, 18) (75000, 18)
1 1493.519686460495
0.9828564705882353 0.9788933333333333 0.9784 1518.373877286911
data 0.1875624656677246
(425000, 18) (75000, 18) (75000, 18)
2 1190.0169143676758
0.9825576470588235 0.97812 0.9777733333333334 1215.2295227050781
data 0.18935227394104004
(425000, 18) (75000, 18) (75000, 18)
3 1236.7442524433136
0.98404 0.97932 0.9793333333333333 1264.108561038971
data 0.21818065643310547
(425000, 18) (75000, 18) (75000, 18)
4 2142.5663521289825
0.9840611764705882 0.9807333333333333 0.9795466666666667 2205.8330075740814
Best Test Accuracy is : 0.9812

   Fold.no  Training Score  Validation Score  Test Score
0      0.0        0.984882          0.981173    0.981200
1      1.0        0.982856          0.978893    0.978400
2      2.0        0.982558          0.978120    0.977773
3      3.0        0.984040          0.979320    0.979333
4      4.0        0.984061          0.980733    0.979547

In [10]:
from sklearn.metrics import confusion_matrix
cls=classifiers[0]
y_t=list(y_test)
tey_pred = cls.predict(X_test)
cm2 = confusion_matrix(y_t, list(tey_pred))
cm_df2 = pd.DataFrame(cm2,index = activity_id.values(),columns = activity_id.values())
print("Confusion Matrix")
cm_df2

Confusion Matrix

,lying,sitting,standing,walking,running,cycling,Nordic walking,ascending stairs,descending stairs,vacuum cleaning,ironing,rope jumping
lying,28775,8,1,4,0,0,0,1,0,9,14,0
sitting,3,27687,78,0,0,0,0,0,5,11,5,0
standing,0,13,28037,0,0,0,0,0,0,138,277,0
walking,0,0,0,35061,0,2,129,206,7,210,0,0
running,0,0,0,18,14724,1,3,12,36,2,0,43
cycling,0,0,0,12,1,24718,31,26,22,9,0,0
Nordic walking,0,0,0,109,1,52,28122,0,0,7,0,0
ascending stairs,0,0,0,130,0,0,0,16193,884,306,0,0
descending stairs,0,0,1,21,0,16,0,1219,14212,187,56,0
vacuum cleaning,0,1,62,28,0,2,0,279,83,25477,402,0
ironing,0,2,46,0,0,0,0,6,21,416,35263,0
rope jumping,0,0,0,1,33,1,0,0,1,0,0,7452