In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
files=["subject102.DAT","subject103.DAT","subject104.DAT","subject105.DAT","subject106.DAT","subject107.DAT","subject108.DAT","subject109.DAT"]
data=pd.read_csv("PAMAP2_Dataset\Protocol\subject101.DAT",sep=" ",header=None)
data=data.interpolate(method ='linear', limit_direction ='forward').copy()
for i in range(len(files)):
    path="PAMAP2_Dataset//Protocol//"+files[i]
    temp=pd.read_csv(path,sep=" ",header=None)
    temp=temp.interpolate(method ='linear').copy()
    data=data.append(temp, ignore_index=True)

C:\Users\vivek\AppData\Local\Temp\ipykernel_5440\89756712.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)
C:\Users\vivek\AppData\Local\Temp\ipykernel_5440\89756712.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)
C:\Users\vivek\AppData\Local\Temp\ipykernel_5440\89756712.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)
C:\Users\vivek\AppData\Local\Temp\ipykernel_5440\89756712.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)
C:\Users\vivek\AppData\Local\Temp\ipykernel_5440\89756712.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)
C:\Users\vivek\AppData\Local\Temp\ipykernel_5440\89756712.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)
C:\Users\vivek\AppData\Local\Temp\ipykernel_5440\89756712.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)
C:\Users\vivek\AppData\Local\Temp\ipykernel_5440\89756712.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append(temp, ignore_index=True)

In [3]:
data.rename(columns = {1:'activity'}, inplace = True)
data

,0,activity,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
0,8.38,0,104.0,30.0000,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.008300,0.009250,-0.017580,-61.1888,-38.95990,-58.143800,1.000000,0.000000,0.000000,0.000000
1,8.39,0,104.0,30.0000,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.006577,-0.004638,0.000368,-59.8479,-38.89190,-58.525300,1.000000,0.000000,0.000000,0.000000
2,8.40,0,104.0,30.0000,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.003014,0.000148,0.022495,-60.7361,-39.41380,-58.399900,1.000000,0.000000,0.000000,0.000000
3,8.41,0,104.0,30.0000,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,0.003175,-0.020301,0.011275,-60.4091,-38.76350,-58.395600,1.000000,0.000000,0.000000,0.000000
4,8.42,0,104.0,30.0000,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,0.012698,-0.014303,-0.002823,-61.5199,-39.38790,-58.269400,1.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2872528,100.19,0,161.0,25.1875,-4.71493,10.22250,4.66893,-5.04654,9.94944,4.50736,...,-0.037788,-0.062676,-0.127084,-46.5153,3.58240,-0.035995,0.598531,0.033615,0.799791,-0.031075
2872529,100.20,0,161.0,25.1875,-4.95932,10.37130,4.12594,-4.96890,10.29620,4.43102,...,-0.068904,-0.027006,-0.089808,-45.7474,3.54453,0.108583,0.598428,0.033012,0.799933,-0.030018
2872530,100.21,0,161.0,25.1875,-4.93997,9.83615,3.70468,-5.04613,10.35690,4.14405,...,-0.070888,-0.038024,-0.064709,-46.3997,4.22078,0.105504,0.598233,0.033172,0.800095,-0.029416
2872531,100.22,0,161.0,25.1875,-4.64941,9.11129,3.51904,-5.06854,9.75268,3.87359,...,0.018961,-0.025796,-0.064357,-46.5282,4.48593,0.530240,0.598116,0.033427,0.800180,-0.029208
2872532,100.23,0,161.0,25.1875,-4.09726,8.15642,3.29961,-4.73244,8.82870,3.54305,...,-0.027472,0.011866,-0.042858,-46.2704,4.21475,0.247798,0.598119,0.033685,0.800188,-0.028602

In [4]:
data=data.dropna() 
data.shape

activity_id = {1:'lying', 2:'sitting', 3:'standing',
              4:'walking', 5:'running', 6:'cycling', 7:'Nordic walking', 
              12:'ascending stairs', 13:'descending stairs', 16:'vacuum cleaning',
              17:'ironing', 24:'rope jumping'}
data=data[data['activity'].isin(activity_id.keys())]
data

,0,activity,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
2928,37.66,1,100.0,30.375,2.21530,8.27915,5.58753,2.24689,8.55387,5.77143,...,0.002908,-0.027714,0.001752,-61.1081,-36.863600,-58.369600,1.000000,0.000000,0.000000,0.000000
2929,37.67,1,100.0,30.375,2.29196,7.67288,5.74467,2.27373,8.14592,5.78739,...,0.020882,0.000945,0.006007,-60.8916,-36.319700,-58.365600,1.000000,0.000000,0.000000,0.000000
2930,37.68,1,100.0,30.375,2.29090,7.14240,5.82342,2.26966,7.66268,5.78846,...,-0.035392,-0.052422,-0.004882,-60.3407,-35.784200,-58.611900,1.000000,0.000000,0.000000,0.000000
2931,37.69,1,100.0,30.375,2.21800,7.14365,5.89930,2.22177,7.25535,5.88000,...,-0.032514,-0.018844,0.026950,-60.7646,-37.102800,-57.879900,1.000000,0.000000,0.000000,0.000000
2932,37.70,1,100.0,30.375,2.30106,7.25857,6.09259,2.20720,7.24042,5.95555,...,0.001351,-0.048878,-0.006328,-60.2040,-37.122500,-57.884700,1.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2872015,95.06,24,162.0,25.125,4.99466,6.01881,5.59830,4.90787,6.05780,5.68357,...,0.021288,-0.012885,0.005878,-45.7855,-0.831734,-0.170139,0.522929,-0.291612,0.705786,-0.378648
2872016,95.07,24,162.0,25.125,5.02764,5.90369,5.48372,4.89090,5.95209,5.56301,...,0.010715,0.003629,-0.004235,-46.0331,-0.817288,0.538134,0.522880,-0.291694,0.705895,-0.378450
2872017,95.08,24,162.0,25.125,5.06409,5.71370,5.48491,4.97981,5.87584,5.45738,...,-0.016939,-0.035176,-0.002309,-45.5140,-1.229410,0.540438,0.522625,-0.291978,0.706161,-0.378084
2872018,95.09,24,162.0,25.125,5.13914,5.63724,5.48629,4.97690,5.69448,5.29167,...,-0.028069,-0.036457,-0.007076,-45.9093,-0.565555,0.680109,0.522536,-0.291955,0.706426,-0.377733
2872019,95.10,24,162.0,25.125,5.00812,5.40645,5.02326,4.97362,5.45272,5.14120,...,-0.013310,-0.030195,0.018229,-46.1702,-0.812965,-0.313346,0.522730,-0.291275,0.706526,-0.377800

In [5]:
from sklearn.model_selection import train_test_split
y=data[data.columns[1]]
X=data[data.columns[2:]]
for i in X.columns:
    X[i] = (X[i] - X[i].mean()) / X[i].std()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)

C:\Users\vivek\AppData\Local\Temp\ipykernel_5440\1556569103.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[i] = (X[i] - X[i].mean()) / X[i].std()

In [6]:
X_test

,2,3,4,5,6,7,8,9,10,11,...,44,45,46,47,48,49,50,51,52,53
1195119,-0.166265,0.521827,-0.887456,-0.549762,-0.813313,-0.820867,-0.423346,-0.929230,-0.624116,-0.251519,...,0.295064,0.437035,-0.093092,0.410621,-1.889209,0.216137,0.153115,-1.241332,-1.019389,-1.021706
1918099,-0.166265,0.765674,-0.176531,0.162486,-2.600110,-0.184403,0.332406,-2.319452,-0.509853,-0.484227,...,-0.153158,-0.731137,-0.195454,-1.228268,0.130895,-0.597897,0.898679,0.293372,1.288077,0.353691
1686094,0.833975,1.079191,0.415119,-0.141233,-0.911392,0.539384,-0.249290,-0.897603,0.009764,-0.242831,...,-0.216433,-0.889674,-0.606543,-0.137765,-0.806144,1.414892,-0.787094,-1.440704,-0.755101,-0.992415
394387,-1.166504,0.521827,1.907785,-0.160403,0.631586,1.926230,-0.173095,0.689279,0.003413,-0.094142,...,-0.024058,0.069040,0.015311,1.061855,1.032834,-1.054844,-0.640315,0.535830,1.372935,-1.023286
570069,-0.388540,0.626333,-0.629303,0.055050,-0.577335,-0.713806,-0.002176,-0.555616,1.225828,0.223774,...,-0.058081,0.153701,0.008860,-0.005990,-0.908487,1.022109,0.834105,-0.729199,0.977150,0.430889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329726,2.426950,-1.289603,1.536781,0.607939,-1.375627,1.561742,0.479132,-1.357684,-0.460855,2.210307,...,-0.494730,1.320042,-1.520434,-1.365222,0.675201,0.881455,2.037571,0.015747,-0.908957,0.118701
122611,0.537608,0.452157,0.248931,0.587491,0.354573,0.190572,0.535263,0.275869,-0.157363,-0.160038,...,-0.162401,-0.143084,0.032870,-0.450126,1.618181,-0.282728,2.037571,0.015747,-0.908957,0.118701
748470,0.352378,-1.846966,0.222856,-0.266951,1.127371,0.254360,-0.400009,0.681330,0.237118,0.217345,...,-0.364136,-0.396015,0.641539,-0.532933,0.622399,0.240109,0.143092,1.144505,0.773779,0.744442
494497,-0.833091,0.939850,0.116826,0.421209,1.013832,0.239447,0.439085,1.015314,-1.176915,1.359561,...,0.099057,-0.108639,0.034140,-0.213088,0.275142,1.257416,-1.007971,1.403207,-0.805778,1.376527
2356801,-0.277402,0.034135,-1.214797,0.037629,-0.493796,-1.222358,0.003655,-0.451405,0.045161,-0.447067,...,-2.104938,1.002303,-0.694491,-1.199734,0.849095,-0.195676,0.431201,0.719173,1.350243,0.339525

In [7]:
tx1=X_train[:int(len(X_train)/5)].copy()
tx2=X_train[int(len(X_train)/5):int(2*len(X_train)/5)].copy()
tx3=X_train[int(2*len(X_train)/5):int(3*len(X_train)/5)].copy()
tx4=X_train[int(3*len(X_train)/5):int(4*len(X_train)/5)].copy()
tx5=X_train[int(4*len(X_train)/5):].copy()
ty1=y_train[:int(len(y_train)/5)].copy()
ty2=y_train[int(len(y_train)/5):int(2*len(y_train)/5)].copy()
ty3=y_train[int(2*len(y_train)/5):int(3*len(y_train)/5)].copy()
ty4=y_train[int(3*len(y_train)/5):int(4*len(y_train)/5)].copy()
ty5=y_train[int(4*len(y_train)/5):].copy()
training_x=[tx1,tx2,tx3,tx4,tx5]
training_y=[ty1,ty2,ty3,ty4,ty5]

In [8]:
def data(i):
    temp_x=pd.DataFrame()
    temp_y=pd.DataFrame()
    val_x=pd.DataFrame()
    val_y=pd.DataFrame()
    for j in range(5):
        if (i!=j):
            temp_x=pd.concat([temp_x,training_x[j]])
            temp_y=pd.concat([temp_y,training_y[j]])
        else:
            val_x=pd.concat([val_x,training_x[j]])
            val_y=pd.concat([val_y,training_y[j]])
    return temp_x,temp_y,val_x,val_y

In [9]:
from sklearn.linear_model import RidgeClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
scores=pd.DataFrame(columns=["Fold.no","Training Score","Validation Score","Test Score"])
classifiers=[]
#pca = PCA(n_components=17)
for i in range(5):
    data_x,data_y,v_x,v_y=data(i)
    #x1=pca.fit_transform(data_x)
    #x2=pca.fit_transform(v_x)
    #x3=pca.fit_transform(X_test)
    classifier = RidgeClassifier(alpha=0.01,solver="sag")
    classifier.fit(data_x, data_y)
    vy_pred = classifier.predict(v_x)
    sc2=accuracy_score(v_y, vy_pred)
    try_pred = classifier.predict(data_x)
    sc1=accuracy_score(data_y, try_pred)
    tey_pred = classifier.predict(X_test)
    sc3=accuracy_score(y_test, tey_pred)
    classifiers.append(classifier)
    scores.loc[len(scores)]=[i,sc1,sc2,sc3]
    print(i)
print("Best Test Accuracy is :", max(scores['Test Score']))
scores

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:1059: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:1059: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

1

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:1059: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

2

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:1059: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

3

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:1059: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

4
Best Test Accuracy is : 0.7160562877662294

   Fold.no  Training Score  Validation Score  Test Score
0      0.0        0.717162          0.716608    0.715682
1      1.0        0.716831          0.717213    0.715552
2      2.0        0.717313          0.717625    0.715909
3      3.0        0.717451          0.717002    0.716056
4      4.0        0.717347          0.717178    0.715957

In [10]:
from sklearn.metrics import confusion_matrix
cls=classifiers[3]
y_t=list(y_test)
tey_pred = cls.predict(X_test)
cm2 = confusion_matrix(y_t, list(tey_pred))
cm_df2 = pd.DataFrame(cm2,index = activity_id.values(),columns = activity_id.values())
print("Confusion Matrix")
cm_df2

Confusion Matrix

,lying,sitting,standing,walking,running,cycling,Nordic walking,ascending stairs,descending stairs,vacuum cleaning,ironing,rope jumping
lying,26941,351,815,111,0,37,8,12,0,220,317,0
sitting,330,22731,621,42,3,94,0,0,2,389,3577,0
standing,44,1723,21024,117,5,0,0,1,0,248,5303,0
walking,13,51,395,32955,1,738,731,70,16,272,373,0
running,48,303,303,608,9660,518,1531,473,514,198,480,203
cycling,2,68,3,234,25,23012,185,151,71,144,924,0
Nordic walking,174,819,540,10148,1217,2374,10504,575,184,390,1291,75
ascending stairs,69,315,2018,3454,770,384,567,5784,651,2675,825,1
descending stairs,118,528,883,4844,532,668,841,996,3436,1030,1836,0
vacuum cleaning,41,1579,1236,1066,65,659,26,177,73,17994,3418,0
ironing,0,404,1387,13,0,50,0,0,0,215,33685,0
rope jumping,7,99,114,126,4023,662,1085,247,68,100,2,955

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
scores=pd.DataFrame(columns=["Fold.no","Training Score","Validation Score","Test Score"])
classifiers=[]
#pca = PCA(n_components=17)
for i in range(5):
    data_x,data_y,v_x,v_y=data(i)
    #x1=pca.fit_transform(data_x)
    #x2=pca.fit_transform(v_x)
    #x3=pca.fit_transform(X_test)
    classifier = LogisticRegression(C=0.01,solver="sag")
    classifier.fit(data_x, data_y)
    vy_pred = classifier.predict(v_x)
    sc2=accuracy_score(v_y, vy_pred)
    try_pred = classifier.predict(data_x)
    sc1=accuracy_score(data_y, try_pred)
    tey_pred = classifier.predict(X_test)
    sc3=accuracy_score(y_test, tey_pred)
    classifiers.append(classifier)
    scores.loc[len(scores)]=[i,sc1,sc2,sc3]
    print(i)
print("Best Test Accuracy is :", max(scores['Test Score']))
scores

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

1

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

2

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

3

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

4
Best Test Accuracy is : 0.8569129570979065

   Fold.no  Training Score  Validation Score  Test Score
0      0.0        0.857759          0.857143    0.856625
1      1.0        0.857720          0.857630    0.856748
2      2.0        0.857883          0.857567    0.856913
3      3.0        0.857608          0.857842    0.856662
4      4.0        0.857490          0.857703    0.856498

In [12]:
cls=classifiers[2]
y_t=list(y_test)
tey_pred = cls.predict(X_test)
cm2 = confusion_matrix(y_t, list(tey_pred))
cm_df2 = pd.DataFrame(cm2,index = activity_id.values(),columns = activity_id.values())
print("Confusion Matrix")
cm_df2

Confusion Matrix

,lying,sitting,standing,walking,running,cycling,Nordic walking,ascending stairs,descending stairs,vacuum cleaning,ironing,rope jumping
lying,28055,52,316,0,82,0,0,2,0,148,113,44
sitting,187,26116,921,77,0,0,0,2,0,318,168,0
standing,17,523,25395,1,0,0,0,1,5,817,1702,4
walking,3,0,42,31917,1,102,1855,667,1010,10,8,0
running,21,2,9,216,11622,149,785,570,322,128,20,995
cycling,0,0,0,70,99,23473,508,277,242,147,1,2
Nordic walking,20,13,20,2365,80,367,23140,906,1083,39,111,147
ascending stairs,161,17,339,1575,728,184,1081,10469,1516,1272,86,85
descending stairs,86,53,30,2344,314,429,1292,2091,8139,742,87,105
vacuum cleaning,98,461,690,510,61,104,73,517,453,22045,1322,0
ironing,0,202,1289,0,0,50,1,32,28,432,33720,0
rope jumping,7,3,1,5,1070,54,484,209,10,2,3,5640